# Generated by Django 5.1.3 on 2024-11-14 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_employee_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='deactivated_at',
        ),
    ]
